#!/usr/bin/env bash

prefix="vcwc_confluent_kafka_connect_sasl_traefik__$1"
prefix="vcwc_confluent_kafka_connect_sasl_traefik__$1"

if [[ "vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_secrets_volume
fi

if [[ "vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_connect_secrets_volume
fi

if [[ "vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_data_volume
fi

if [[ "vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_confluent_kafka_connect_sasl_traefik__kz_kafka_connect_jars_volume
fi
