---
version: '3'
services:

# START SERVICE vcwc/confluent/kafka_rest
  kafka_rest:
    image: ${VCW_REGISTRY}confluentinc/cp-kafka-rest:6.0.0
    environment: ['KAFKA_REST_HOST_NAME=kafka_rest','KAFKA_REST_BOOTSTRAP_SERVERS=kafka:9092','KAFKA_REST_LISTENERS=http://0.0.0.0:8082','KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema_registry:8081']
    command: []
    volumes: []
    ports: [${VCW_STACK_KAFKA_REST_PORTS}]
    networks: [${VCW_STACK_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${VCW_STACK_KAFKA_REST_DEPLOY_MODE}
      resources:
        limits:
          memory: '${VCW_STACK_KAFKA_REST_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_KAFKA_REST_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_KAFKA_REST_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/confluent/kafka_rest

networks: {${VCW_STACK_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
