#!/usr/bin/env bash

prefix="vcwc_confluent_kafka_connect__$1"
prefix="vcwc_confluent_kafka_connect__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_confluent_kafka_connect__kz_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_confluent_kafka_connect__kz_kafka_connect_secrets_volume"
		result=$(docker volume ls | grep "vcwc_confluent_kafka_connect__kz_kafka_connect_secrets_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_confluent_kafka_connect__kz_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_confluent_kafka_connect__kz_kafka_connect_connect_secrets_volume"
		result=$(docker volume ls | grep "vcwc_confluent_kafka_connect__kz_kafka_connect_connect_secrets_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_confluent_kafka_connect__kz_kafka_connect_data_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_confluent_kafka_connect__kz_kafka_connect_data_volume"
		result=$(docker volume ls | grep "vcwc_confluent_kafka_connect__kz_kafka_connect_data_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_confluent_kafka_connect__kz_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_confluent_kafka_connect__kz_kafka_connect_jars_volume"
		result=$(docker volume ls | grep "vcwc_confluent_kafka_connect__kz_kafka_connect_jars_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
