---
version: '3'
services:

# START SERVICE vcwc/confluent/ksqldb
  ksqldb:
    image: ${VCW_REGISTRY}confluentinc/ksqldb-server:6.0.0
    environment: ['KSQL_BOOTSTRAP_SERVERS=${KAFKA_REST_MODULE_BOOTSTRAP_SERVERS}','KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE=true','KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE=true','KSQL_KSQL_SERVICE_ID=${KAFKA_REST_MODULE_KSQL_SERVICE_ID}'${KAFKA_REST_MODE}]
    command: []
    volumes: [${VCW_STACK_GLOBAL_STACKPREFIX}_ksql_server_queries_volume:/vcw/pwd]
    ports: [${KAFKA_REST_PORTS}]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${KAFKA_REST_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${KAFKA_REST_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${KAFKA_REST_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/confluent/ksqldb

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_ksql_server_queries_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
