---
version: '3'
services:

# START SERVICE vcwc/confluent/ksqldb
  ksqldb:
    image: ${VCW_REGISTRY}confluentinc/ksqldb-server:6.0.0
    environment: ['KSQL_BOOTSTRAP_SERVERS=${VCW_STACK_KSQL_SERVER_KSQL_BOOTSTRAP_SERVERS}','KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE=true','KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE=true','KSQL_KSQL_SERVICE_ID=${VCW_STACK_KSQL_SERVER_KSQL_KSQL_SERVICE_ID}'${VCW_STACK_KSQL_SERVER_MODE}]
    command: []
    volumes: [${VCW_STACK_STACKPREFIX}_ksql_server_queries_volume:/conteco/pwd]
    ports: [${VCW_STACK_KSQL_SERVER_PORTS}]
    networks: [${VCW_STACK_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_KSQL_SERVER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_KSQL_SERVER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_KSQL_SERVER_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/confluent/ksqldb

networks: {${VCW_STACK_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_STACKPREFIX}_ksql_server_queries_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
