---
version: '3'
services:

# START SERVICE vcwc/confluent/zookeeper
  zookeeper:
    image: ${VCW_REGISTRY}confluentinc/cp-zookeeper:6.0.0
    environment: ['ZOOKEEPER_CLIENT_PORT=2181','ZOOKEEPER_TICK_TIME=2000']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_zookeeper_secrets_volume:/etc/zookeeper/secrets','${VCW_STACK_GLOBAL_STACKPREFIX}_zookeeper_data_volume:/var/lib/zookeeper/data','${VCW_STACK_GLOBAL_STACKPREFIX}_zookeeper_log_volume:/var/lib/zookeeper/log']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_ZOOKEEPER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_ZOOKEEPER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_ZOOKEEPER_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/confluent/zookeeper

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_zookeeper_secrets_volume: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_zookeeper_data_volume: { external: true },${VCW_STACK_GLOBAL_STACKPREFIX}_zookeeper_log_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
