#!/usr/bin/env bash

prefix="vcwc_confluent_ksqldb_sasl_traefik__$1"
prefix="vcwc_confluent_ksqldb_sasl_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_confluent_ksqldb_sasl_traefik__kafka_rest_ksql_server_queries_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_confluent_ksqldb_sasl_traefik__kafka_rest_ksql_server_queries_volume"
		result=$(docker volume ls | grep "vcwc_confluent_ksqldb_sasl_traefik__kafka_rest_ksql_server_queries_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
