---
version: '3'
services:

# START SERVICE vcwc/confluent/controlcenter/sasl
  controlcenter:
    image: ${VCW_REGISTRY}confluentinc/cp-enterprise-control-center:6.0.0
    environment: ['CONTROL_CENTER_REPLICATION_FACTOR=3','CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION=3','CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION=3','CONTROL_CENTER_COMMAND_TOPIC_REPLICATION=3','CONTROL_CENTER_METRICS_TOPIC_REPLICATION=3','CONFLUENT_METRICS_TOPIC_REPLICATION=3','CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS=3','CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1','CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1','CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES=8388608','CONTROL_CENTER_BOOTSTRAP_SERVERS=${CCENTER_ENVIRONMENT_BOOTSTRAP_SERVERS}','CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL=SASL_SSL','CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${CCENTER_ENVIRONMENT_STREAMS_API_KEY}" password="${CCENTER_ENVIRONMENT_STREAMS_API_SECRET}";','CONTROL_CENTER_STREAMS_SASL_MECHANISM=PLAIN','CONTROL_CENTER_STREAMS_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https','CONTROL_CENTER_SCHEMA_REGISTRY_URL=${CCENTER_ENVIRONMENT_SCHEMA_REGISTRY_URL}','CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO','CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO=${CCENTER_ENVIRONMENT_SCHEMA_REGISTRY_API_KEY}:${CCENTER_ENVIRONMENT_SCHEMA_REGISTRY_API_SECRET}','CONTROL_CENTER_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL=SASL_SSL','CONTROL_CENTER_MONITORING_INTERCEPTOR_SASL_MECHANISM=PLAIN','CONTROL_CENTER_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="<api-key>" password="<api-secret>";','CONTROL_CENTER_MONITORING_INTERCEPTOR_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https','CONTROL_CENTER_CONNECT_CLUSTER=${CCENTER_KAFKA_CONNECT}','CONTROL_CENTER_CONNECT_CLUSTER_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO','CONTROL_CENTER_CONNECT_CLUSTER_BASIC_AUTH_USER_INFO=${CCENTER_ENVIRONMENT_CONNECT_CLUSTER_API_KEY}:${CCENTER_ENVIRONMENT_CONNECT_CLUSTER_API_SECRET}','CONTROL_CENTER_KSQL_KSQLDB1_URL=${CCENTER_ENVIRONMENT_KSQL_URL}','CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL=${CCENTER_ENVIRONMENT_KSQL_ADVERTISED_URL}','CONTROL_CENTER_KSQL_KSQLDB1_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO','CONTROL_CENTER_KSQL_KSQLDB1_BASIC_AUTH_USER_INFO=${CCENTER_ENVIRONMENT_KSQL_API_KEY}:${CCENTER_ENVIRONMENT_KSQL_API_SECRET}']
    command: []
    volumes: []
    ports: [${CCENTER_PORTS}]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${CCENTER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CCENTER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CCENTER_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/confluent/controlcenter/sasl

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
