#!/usr/bin/env bash

# START CONFIGURATION
DOLLAR='$'
export VCW_MODULE_PACKAGES="\
kafka_rest:vcwc/confluent/kafka_rest/sasl/traefik"
# END CONFIGURATION

# START OTHER SETTINGS
export KAFKA_REST_MODULE_KAFKA_REST_PORT="8082"
# END OTHER SETTINGS

