#!/usr/bin/env bash

prefix="vcwc_confluent_schema_registry_traefik__$1"
prefix="vcwc_confluent_schema_registry_traefik__$1"

if [[ "vcwc_confluent_schema_registry_traefik__schema_registry_nginx_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_confluent_schema_registry_traefik__schema_registry_nginx_config_volume
fi

if [[ "vcwc_confluent_schema_registry_traefik__schema_registry_nginx_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_confluent_schema_registry_traefik__schema_registry_nginx_config_volume:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/confluent/schema_registry/traefik/_module/volumes/schema_registry_nginx_config_volume/* /vcw/pwd
fi
