#!/usr/bin/env bash

prefix="vcwc_confluent_schema_registry_sasl__$1"
prefix="vcwc_confluent_schema_registry_sasl__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_confluent_schema_registry_sasl__schema_registry_schema_registry_secrets_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_confluent_schema_registry_sasl__schema_registry_schema_registry_secrets_volume"
		result=$(docker volume ls | grep "vcwc_confluent_schema_registry_sasl__schema_registry_schema_registry_secrets_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
