#!/usr/bin/env bash

prefix="vcwc_confluent_schema_registry_sasl__$1"
prefix="vcwc_confluent_schema_registry_sasl__$1"

if [[ "vcwc_confluent_schema_registry_sasl__schema_registry_schema_registry_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_confluent_schema_registry_sasl__schema_registry_schema_registry_secrets_volume
fi
